// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSLVUB9h39VOffLqbfxS6U2U6zX5r7dFc',
    appId: '1:195226807523:web:ebbc6d6924bacc5b75a9d6',
    messagingSenderId: '195226807523',
    projectId: 'campets-a3bdf',
    authDomain: 'campets-a3bdf.firebaseapp.com',
    databaseURL: 'https://campets-a3bdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campets-a3bdf.firebasestorage.app',
    measurementId: 'G-91PTVJYCH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbqwC3Qa66GC8HVBGgN2JIqBBCy5DHrl4',
    appId: '1:195226807523:android:8bd497690ac13ce575a9d6',
    messagingSenderId: '195226807523',
    projectId: 'campets-a3bdf',
    databaseURL: 'https://campets-a3bdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campets-a3bdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6w1zMPukDVFg_hCQh26FS54mirTPdIic',
    appId: '1:195226807523:ios:61522c3d25e4987375a9d6',
    messagingSenderId: '195226807523',
    projectId: 'campets-a3bdf',
    databaseURL: 'https://campets-a3bdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campets-a3bdf.firebasestorage.app',
    iosBundleId: 'com.example.newcampets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6w1zMPukDVFg_hCQh26FS54mirTPdIic',
    appId: '1:195226807523:ios:61522c3d25e4987375a9d6',
    messagingSenderId: '195226807523',
    projectId: 'campets-a3bdf',
    databaseURL: 'https://campets-a3bdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campets-a3bdf.firebasestorage.app',
    iosBundleId: 'com.example.newcampets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSLVUB9h39VOffLqbfxS6U2U6zX5r7dFc',
    appId: '1:195226807523:web:fc8878b095feda1275a9d6',
    messagingSenderId: '195226807523',
    projectId: 'campets-a3bdf',
    authDomain: 'campets-a3bdf.firebaseapp.com',
    databaseURL: 'https://campets-a3bdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campets-a3bdf.firebasestorage.app',
    measurementId: 'G-NT5GKL2M3J',
  );

}